title_primary: "代码 · 生活 · 感悟" # the bigger text
title_secondary: "Typography" # the smaller text
keywords:

twitter: #username
rss: #atom.xml
weibo: #username/id
instagram: #username
github: Lauweal

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: disqus_69Kn97UzBv
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark